# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmy9e-a14JBPFKSRXMAWKDHtDIF1M_y_
"""

import os

from flask import Flask, request, jsonify, render_template
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.models import VectorizedQuery
from openai import AzureOpenAI


# =========================================================
# Flask
# =========================================================

app = Flask(__name__)


# =========================================================
# Azure AI Search
# =========================================================

SEARCH_ENDPOINT = "https://aisearchtraining0.search.windows.net"
SEARCH_KEY = os.environ["AZURE_SEARCH_KEY"]
SEARCH_INDEX = os.environ["AZURE_SEARCH_INDEX"]


# =========================================================
# Azure OpenAI
# =========================================================

OPENAI_ENDPOINT = "https://openai-training.openai.azure.com/"
OPENAI_KEY = os.environ["AZURE_OPENAI_KEY"]
OPENAI_DEPLOYMENT = "gpt-5.4-mini"

# اسم Deployment الخاص بالـ Embedding Model
EMBEDDING_DEPLOYMENT = os.environ[
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT"
]


# =========================================================
# Azure Search Vector Field
# =========================================================

VECTOR_FIELD = os.environ.get(
    "AZURE_SEARCH_VECTOR_FIELD",
    "contentVector"
)


# =========================================================
# Azure AI Search Client
# =========================================================

search_client = SearchClient(
    endpoint=SEARCH_ENDPOINT,
    index_name=SEARCH_INDEX,
    credential=AzureKeyCredential(SEARCH_KEY)
)


# =========================================================
# Azure OpenAI Client
# =========================================================

openai_client = AzureOpenAI(
    azure_endpoint=OPENAI_ENDPOINT,
    api_key=OPENAI_KEY,
    api_version="2025-04-01-preview"
)


# =========================================================
# Home Page
# =========================================================

@app.route("/", methods=["GET"])
def home():

    return render_template("index.html")


# =========================================================
# Health Check
# =========================================================

@app.route("/health", methods=["GET"])
def health():

    return jsonify({
        "status": "ok",
        "message": "RAG API is running"
    })


# =========================================================
# Ask
# =========================================================

@app.route("/ask", methods=["POST"])
def ask():

    data = request.get_json()

    if not data or "question" not in data:

        return jsonify({
            "error": "Please provide a question."
        }), 400


    question = data["question"].strip()

    if not question:

        return jsonify({
            "error": "Question cannot be empty."
        }), 400


    # =====================================================
    # Create embedding for the question
    # =====================================================

    embedding_response = openai_client.embeddings.create(
        model=EMBEDDING_DEPLOYMENT,
        input=question
    )

    query_vector = embedding_response.data[0].embedding


    # =====================================================
    # Hybrid Search
    # Keyword + Vector
    # =====================================================

    vector_query = VectorizedQuery(
        vector=query_vector,
        k_nearest_neighbors=5,
        fields=VECTOR_FIELD
    )


    results = search_client.search(
        search_text=question,
        vector_queries=[vector_query],
        top=5
    )


    # =====================================================
    # Build Context
    # =====================================================

    context_parts = []
    sources = []

    for result in results:

        content = result.get("content")

        if not content:
            continue

        source = result.get(
            "source",
            "Unknown"
        )

        page = result.get(
            "page",
            "Unknown"
        )

        context_parts.append(
            f"Source: {source}\n"
            f"Page: {page}\n"
            f"Content:\n{content}"
        )

        sources.append({
            "source": source,
            "page": page
        })


    context = "\n\n".join(context_parts)


    # =====================================================
    # No Context
    # =====================================================

    if not context:

        return jsonify({
            "question": question,
            "answer": (
                "The answer is not available "
                "in the provided documents."
            ),
            "sources": []
        })


    # =====================================================
    # Prompt
    # =====================================================

    system_prompt = """
You are a GenAI RAG assistant.

Answer the user's question using ONLY the
information contained in the provided context.

Rules:

1. Do not use outside knowledge.
2. Do not invent information.
3. If the answer is not available in the context,
   say:

   "The answer is not available in the provided documents."

4. Give a clear and concise answer.
5. Use the retrieved documents as the only source.
"""


    user_prompt = f"""
Question:
{question}

Retrieved Context:
{context}
"""


    # =====================================================
    # Azure OpenAI
    # =====================================================

    response = openai_client.chat.completions.create(

        model=OPENAI_DEPLOYMENT,

        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ],

        temperature=0
    )


    answer = response.choices[0].message.content


    # =====================================================
    # Remove Duplicate Sources
    # =====================================================

    unique_sources = []

    seen = set()

    for source in sources:

        key = (
            source["source"],
            source["page"]
        )

        if key not in seen:

            unique_sources.append(source)
            seen.add(key)


    # =====================================================
    # Return Answer
    # =====================================================

    return jsonify({

        "question": question,

        "answer": answer,

        "sources": unique_sources

    })


# =========================================================
# Run Flask
# =========================================================

if __name__ == "__main__":

    port = int(
        os.environ.get(
            "PORT",
            8000
        )
    )

    app.run(
        host="0.0.0.0",
        port=port
    )